language: ruby
cache: bundler
rvm:
- 2.1.1
install: true
env:
  global:
  - SYSTEM_OF_RECORD_API_URL='http://lr-system-of-record.herokuapp.com'
  - MINT_API_URL='http://lr-mint.herokuapp.com'
  - PROPERTY_FRONTEND_URL='http://lr-property-frontend.herokuapp.com'
  - SEARCH_API_URL='http://lr-search-api.herokuapp.com'
  - CASEWORK_FRONTEND_URL='http://lr-casework-frontend.herokuapp.com'
  - PUBLIC_TITLES_API_URL='http://lr-public-titles-api.herokuapp.com'
  - PRIVATE_PROPERTY_FRONTEND_URL='http://coming.soon'
  - secure: "HNwD8WAyV7fazoel0E+X9SCqCttW1VcJjEhEJGVWWWqZeLLkTDg+Z7uRFDdBt9xsCJTFmoGV4SEpypPAb9h/cFeOLcoZrRoCXL0rlh5APT28Xd1h3vcGnDHG7g6MQXwrl5wX1NfmJ9DM+VXPJFgTKSahDfiNOe5/Bfkfs9d0TnU="
  - secure: "TCBTKvMROQKmI4WFO+d35VxJakpV54MhTBTyzFNGRNp1xD0qivwxFWOs0V8/AVWLn6H/F6B7y/s35Vs+jVdHjn6GwQAtoeWgAux2NoypOO9gL/VHlsUjX2B3/UsVVa9MLt992nzZmbABxiNANAqYmU8Qfntx8c19nCA8/sZlO7I="
before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
before_script:
- bundle install
script:
- bundle exec cucumber -p heroku --format json --out report.json
  --format pretty
- curl -X PUT -H 'Content-Type:application/json' -d @/home/travis/build/LandRegistry/service-tests/report.json https://srv-test-dash.firebaseio.com/report.json?auth=$FIREBASE_TOKEN 
